### ISSUE TITLE
Get "too difficult/couldn't see" lines from MapRoulette

### ISSUE THREAD

**Issue by ebrelsford** [osmlab/nycbikelanes#11]
These would be good targets for surveying.

**Comment by bfreeds** [comment]
@ebrelsford Where would one find the delta tables from the MapRoulette challenges?

**Comment by ebrelsford** [comment]
We'll need to use the [MapRoulette API to list tasks](https://github.com/osmlab/maproulette/wiki/API-Documentation#bulk-list-task-statuses), specifically those with `status` = `skipped`. Then we'll need to map the tasks back to the city's line segments.

Less usefully, there are weekly(ish) progress snapshots [here](https://github.com/osmlab/nycbikelanes/tree/master/challenges/city_not_osm/progress) that include which bike lanes still need to be added to OSM according to our buffer-intersect criteria.

**Comment by ebrelsford** [comment]
Added scripts in 4385973a58 and you can see the results in [skipped.geojson](https://github.com/osmlab/nycbikelanes/blob/cd33e7459f6050e5863c92d178baae8e4e60bd68/challenges/city_not_osm/skipped.geojson). It's mostly small segments of road where the aerial imagery was not clear enough to say where the bike lane was. It might make sense to wait until we've mapped a bit more of the [MapRoulette challenge](http://maproulette.org/#t=nycbikelanes-missing) before we survey these.
