### ISSUE TITLE
Script for downloading OSM and city data

### ISSUE THREAD

**Issue by ebrelsford** [osmlab/nycbikelanes#3]
This could be relatively simple like the [Makefile for the NYC buildings import](https://github.com/osmlab/nycbuildings/blob/master/Makefile).

For OSM: Would make sense to download the [Metro Extract](https://mapzen.com/metro-extracts), select the ways we want, and clip to the [NYC borough boundaries](https://data.cityofnewyork.us/City-Government/Borough-Boundaries-Water-Areas-Included-/tv64-9x69). Or we could us [overpass](http://overpass-api.de/).

City data: isn't currently online, we might have to add it to this repo?

**Comment by clhenrick** [comment]
maybe don't simplify the osm data in the Makefile, it creates some odd paths that likely will through off a PostGIS query:
![osm-bike-lane-simplify-error](https://cloud.githubusercontent.com/assets/161748/6341258/b92dfa72-bb96-11e4-8505-0a77dbf1f683.jpg)

**Comment by ebrelsford** [comment]
Yes that's the plan, I have a local version that doesn't do this, will
merge soon!

**Comment by clhenrick** [comment]
Cool!

-Chris

**Comment by ebrelsford** [comment]
The Makefile has been updated to reflect these and other changes.
