### ISSUE TITLE
alter makefile to dl imposm & osm2pgsql data, don't simplify it

### ISSUE THREAD

**Issue by clhenrick** [osmlab/nycbikelanes#4]
![screen shot 2015-03-25 at 8 01 21 pm](https://cloud.githubusercontent.com/assets/161748/6838081/493e7344-d32a-11e4-852a-7b1b1fc986b2.png)
QGIS screen grab showing cycleways from imposm (white), bicycle=yes from osm2pgsql (yellow), and city data (blue) on the very bottom.

We should use both the imposm and osm2pgsql data for determining existing bicycle data, then do a union, buffer, and finally an intersection with the city data.

sound good?

**Comment by clhenrick** [comment]
![screen shot 2015-03-25 at 11 03 19 pm](https://cloud.githubusercontent.com/assets/161748/6839702/1f133532-d343-11e4-9cf7-2087b32aeb5f.png)

Okay so I think the problem is that even with including all existing osm data is that the city data is excluded when it crosses the buffer. In the above screen grab magenta segments are city data not captured by the buffer, orange is existing OSM and blue is all city data. What I think is happening is that the city data's segments are too long so that when they cross an OSM segment they get excluded. We probably don't want this to happen correct?

**Comment by ebrelsford** [comment]
I created a branch where we get the OSM data via Overpass, and I think it's preferable for a few reasons:

 1. We get only the data you want, so we don't have to filter it and it's (much) faster to download.
 2. We don't have to worry about potential duplicate geometries from merging, which could help down the line when we're trying to conflate OSM and CSCL data.

Check out the commit (4ac1d6fa9c). By grabbing the lines that are have any `cycleway` tag from the data to be added, we get rid of ~500 lines, which is pretty exciting!

Let me know how you feel about this and I can merge it if you agree. I think we should start a separate issue for your second comment on this.

**Comment by clhenrick** [comment]
@ebrelsford agreed! I'll open another ticket.
