### ISSUE TITLE
Clear up the meanings of FT_Facilit and TF_Facilit

### ISSUE THREAD

**Issue by ebrelsford** [osmlab/nycbikelanes#5]
It would be helpful to know more about the `FT_Facilit` and `TF_Facilit` fields in the city's (CSCL) data.

Here are the ones we think we might want to skip:
 *  `Potential Bicycle Path`
 *  `Bike-Friendly Parking`
 *  `Removed`

For example, we see that 4th Avenue in Brooklyn is labeled with `FT_Facility` = `Bike-Friendlly Parking`:

![selection_001](https://cloud.githubusercontent.com/assets/375002/6848086/8d0185e0-d3a1-11e4-85b2-2b3895c7fe39.png)

It would be helpful to know what that technically means. Could be interesting to include in a separate challenge potentially. But seems like it's not the first challenge (adding missing bike lanes).

And sometimes `FT_Facilit` and `TF_Facilit` don't match. I'm assuming one's the left side and the other's the right? For example:

![selection_002](https://cloud.githubusercontent.com/assets/375002/6848507/ff54696c-d3a3-11e4-8ecf-67de6c5088de.png)

**Comment by clhenrick** [comment]
I forget, do we have the metadata for the CSCL data? @colinreilly do you have any insights?

-Chris

**Comment by ebrelsford** [comment]
Conor from city planning says:

> Since we do not want to include the potentials, "Potential Bicycle Path" can be removed from the data. For that matter, you can also remove "Potential Bicycle Route." And "Removed" can also be taken out of the data.

> As for "Bike-Friendly Parking," my understanding is that this falls in the category of "Shared Lane" and we should therefore keep it. I believe it indicates a street where the on-street parking allows room for bikes to share the road. DOT has something called a "wide parking lane," which allows space for bikes. This probably falls into the Bike-Friendly Parking category. Aaron can probably clarify this more. My initial reaction is that this should be a part of the challenge of identifying what kind of lane is present. For routing purposes, I don't know that the kind of shared lane matters much. It should be marked "III" in AllClasses and the additional information in TF/FT_Facility is helpful.

> On FT/TF Facility not matching, yes, each indicates one direction on the street. FT is "from-to" and TF is "to-from."

**Comment by clhenrick** [comment]
:+1:

**Comment by ebrelsford** [comment]
744cfa34018 handles this.
