### ISSUE TITLE
CSCL data: links

### ISSUE THREAD

**Issue by ebrelsford** [osmlab/nycbikelanes#9]
How can we best map segments that are currently in the city (CSCL) data as links?

These appear with `ft_facilit` and/or `tf_facilit` = `Link`. There are around 1000 of these in the [current data to add](https://github.com/osmlab/nycbikelanes/blob/master/challenges/city_not_osm/data.geojson). My understanding is that there is no bike lane marked there, but that it's a crossing that cyclists are invited to use to get from one bike lane segment to another. Is that correct?

We need to decide what the most accurate and useful (for routing) way to add these to OSM would be.

@colinreilly any thoughts?

**Comment by colinreilly** [comment]
These were added to establish connectivity for the purpose of routing. Needed to explicitly connect bike lanes to street segments for it to work.


Sent Via DoITT Mobile Device


-------- Original message --------

**Comment by ebrelsford** [comment]
Thanks, I thought so. Are they recognizable on the ground? Signed or labeled somehow?

**Comment by colinreilly** [comment]
No not in many cases. More a construct for the computers. In the field it's figure it out on you own I presume.



On Apr 6, 2015, at 7:21 PM, Eric Brelsford <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, I thought so. Are they recognizable on the ground? Signed or labeled somehow?

�

**Comment by ebrelsford** [comment]
Got it. Thank you!
